# Generated by Django 5.2.2 on 2025-10-03 19:20

import ap_home.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('description_short', models.TextField(verbose_name='Descrição')),
                ('teacher', models.CharField(max_length=255, verbose_name='Professor')),
                ('assessment', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Avaliação')),
                ('quantity_assessment', models.IntegerField(verbose_name='Quantidade de avaliação')),
                ('quantity_hours', models.IntegerField(verbose_name='Quantidade total de horas')),
                ('quantity_classes', models.IntegerField(verbose_name='Quantidade de aulas')),
                ('level', models.CharField(max_length=100, verbose_name='Nível')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=ap_home.models.get_full_path, variations={'thumbnail': {'crop': True, 'height': 250, 'width': 250}})),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
            },
        ),
    ]
